language: go
cache:
  directories:
    - $GOPATH/pkg/mod
install: true
go:
  - 1.13.x
env:
  global:
    - GO111MODULE=on
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.13
before_install:
  - go get -v golang.org/x/lint/golint

script:
  - go test -coverprofile=/tmp/profile.out ./...
  - go tool cover -html=/tmp/profile.out
  - go test --race ./...
  - go vet --all ./...